
name: Verify QuarryProtocol/quarry v1.10.1

on:
  push:
    paths:
      - ".github/workflows/verify-QuarryProtocol__quarry-v1.10.1.yml"

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    name: Release verifiable binaries
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: saber
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Download sources from GitHub
        run: curl -L https://github.com/QuarryProtocol/quarry/archive/refs/tags/v1.10.1.tar.gz > release.tar.gz
      - name: Extract sources
        run: echo $(tar xzvf release.tar.gz | head -1 | cut -f1 -d"/") > dirname
      - name: Perform verifiable build
        run: cd $(cat dirname) && nix shell ../#anchor-0_18_0 --command anchor build --verifiable
      - name: Record program artifacts
        run: |
          mkdir artifacts
          mv $(cat dirname)/target/verifiable/ artifacts/verifiable/
          mv $(cat dirname)/target/idl/ artifacts/idl/

          sha256sum release.tar.gz > artifacts/release-checksums.txt
          sha256sum artifacts/verifiable/* > artifacts/program-checksums.txt
          sha256sum artifacts/idl/* > artifacts/idl-checksums.txt

          echo '# QuarryProtocol/quarry v1.10.1' >> artifacts/README.md
          echo '```' >> artifacts/README.md
          nix shell .#anchor-0_18_0 --command anchor --version >> artifacts/README.md
          date >> artifacts/README.md
          sha256sum release.tar.gz >> artifacts/README.md
          echo '```' >> artifacts/README.md

          echo '## Program checksums' >> artifacts/README.md
          echo '```' >> artifacts/README.md
          sha256sum target/verifiable/* >> artifacts/README.md
          echo '```' >> artifacts/README.md

          echo '## IDL checksums' >> artifacts/README.md
          echo '```' >> artifacts/README.md
          sha256sum target/idl/* > artifacts/README.md
          echo '```' >> artifacts/README.md
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DIST_DEPLOY_KEY }}
          external_repository: DeployDAO/verified-program-artifacts
          publish_branch: verify-QuarryProtocol__quarry-v1.10.1
          publish_dir: ./artifacts/
