
name: Verify saber-hq/merkle-distributor v0.2.2

on:
  push:
    paths:
      - ".github/workflows/verify-saber-hq__merkle-distributor-v0.2.2.yml"

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: "1.7.11"
  RUST_TOOLCHAIN: nightly-2021-09-01

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    name: Release verifiable binaries
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: saber
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Download verifiable tarball of program
        run: |
          curl https://github.com/saber-hq/merkle-distributor/archive/refs/tags/v0.2.2.tar.gz > release.tar.gz
          mkdir build
          cd build
          tar xzvf release.tar.gz

          mkdir artifacts
          nix shell .#ci --command anchor build --verifiable --solana-version 1.7.11
          mv target/verifiable/ artifacts/verifiable/
          mv target/idl/ artifacts/idl/

          sha256sum release.tar.gz > artifacts/release-checksums.txt
          sha256sum target/verifiable/* > artifacts/program-checksums.txt
          sha256sum target/idl/* > artifacts/idl-checksums.txt

          echo '# saber-hq/merkle-distributor v0.2.2' >> artifacts/README.md
          echo '```' >> artifacts/README.md
          anchor --version >> artifacts/README.md
          date >> artifacts/README.md
          sha256sum release.tar.gz >> artifacts/README.md
          echo '```' >> artifacts/README.md

          echo '## Program checksums' >> artifacts/README.md
          echo '```' >> artifacts/README.md
          sha256sum target/verifiable/* >> artifacts/README.md
          echo '```' >> artifacts/README.md

          echo '## IDL checksums' >> artifacts/README.md
          echo '```' >> artifacts/README.md
          sha256sum target/idl/* > artifacts/README.md
          echo '```' >> artifacts/README.md
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DIST_DEPLOY_KEY }}
          external_repository: DeployDAO/verified-program-artifacts
          publish_branch: verify-saber-hq__merkle-distributor-v0.2.2
          publish_dir: ./artifacts/
